
const githubUserConstant ={
    GET_GITHUB_USER_REQUEST: 'GET_GITHUB_USER_REQUEST',
    GET_GITHUB_USER_SUCCESS: 'GET_GITHUB_USER_SUCCESS',
    GET_GITHUB_USER_FAILURE: 'GET_GITHUB_USER_FAILURE',
}

export default githubUserConstant;